# Generated by Django 4.1.7 on 2023-12-04 14:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="US", max_length=2, verbose_name="country"
            ),
        ),
    ]
